
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a4s5d6A4s5!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # JPA의 구현체인 Hibernate가 동작하면서, 발생한 SQL의 가독성을 높여줌.
        format_sql: true
    hibernate:
      # DDL(create, alter, drop) 정의 시, DB의 고유 기능을 사용할 수 있음.
      ddl-auto: create